spring:
  devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
        exclude: static/**,public/**
  datasource:
    url: jdbc:mysql://localhost:3306/trade_pro?serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: l1226441618
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

server:
  address: localhost
  port: 8080
